### ISSUE TITLE
Make interface less confusing for new users

### ISSUE THREAD

**Issue by hackerb9** [tuberry/extension-list#17]
I say "new users", but actually, I've been using extension-list for a long time and I still get confused by the icons and how they work.

Suggestions:
1. Add hover text for all icons describing what action each one will do. 
2. Change the icons to more commonly understood shapes.
    * Use a "[push pin](https://fontawesome.com/v3/icon/pushpin)" icon for pinning extensions.
    * Use an "[eye slash](https://fontawesome.com/v4/icon/eye-slash)" icon  for hiding/unhiding disabled extensions.
    * Use a "[trashcan](https://fontawesome.com/v4/icon/trash)" icon for deleting extensions.
    * Use an "[external link](https://fontawesome.com/v4/icon/external-link)" icon for the URL button.
    * Use a "[bug](https://fontawesome.com/v3/icon/bug)" icon for debugging.
 Also,
    * Although using a puzzle piece icon is good for opening the Gnome Extensions App (or website), it is a bit confusing that it is the same icon already used for Extension List itself. You may want to use the logo from the [Gnome Extensions App](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/subprojects/extensions-app/logo.png) or this [puzzle piece](https://fontawesome.com/v4/icon/puzzle-piece) from Font Awesome.
    * The gear icon for opening an extension's settings is fine, but for consistency of design, you may wish to use Font Awesome's "[cog](https://fontawesome.com/v4/icon/cog)" icon.  
4. Remove the icons from the toolbar on the bottom that toggle which action is available (Delete, URL, and Pin). They are extremely confusing. For example, what button would you push in this image if you wanted to configure the settings for an extension?
    ![image](https://github.com/tuberry/extension-list/assets/10174223/0bc6ec66-f0db-4e92-ad7f-7df0daf8f67f)
    Instead, each extension should have Settings, Delete, and URL icons to the right. Additionally, the Pin icon should be shown when disabled extensions are unhidden.

Thanks and I hope you find these suggestions as helpful as I have found your extension to be.

**Comment by tuberry** [comment]
Thanks for your suggestions.

> 1.  Add hover text for all icons describing what action each one will do.
> 2. Change the icons to more commonly understood shapes. 

The addition of tooltips here will be visually and engineering redundant, and I acknowledge that the main problem is the vague meaning of the icons, and I would prefer to use text labels rather than icons if the area were not narrow. 

`FontAwesome` is a [PUA](https://en.wikipedia.org/wiki/Private_Use_Areas) font and is not installed on all systems, nor is there any guarantee that it will not conflict with other fonts. Fortunately, I have found some more suitable icons in the standard icon pack based on your recommendations.

> Although using a puzzle piece icon is good for opening the Gnome Extensions App (or website), it is a bit confusing that it is the same icon already used for Extension List itself. 

I couldn't find a better replacement for the puzzle icon, but this extension could be seen as an extension to the extension app, and it makes sense to use the same icon. :)

> 3.Remove the icons from the toolbar on the bottom that toggle which action is available (Delete, URL, and Pin). They are extremely confusing.

In the previous version, there were indeed three buttons per extension, but it turned out that the delete and URL buttons were used infrequently and crammed together in a way that made them easy to be clicked by mistake. However, I feel that different icons could be used to indicate their use to reduce confusion.

> Additionally, the Pin icon should be shown when disabled extensions are unhidden.

They are independent of each other. Hiding disabled extension is [requested](https://github.com/tuberry/extension-list/issues/1) by another user. But an unpinned extension means that t does not need to appear in the list, either enabled or disabled.

This is the preliminary solution:

[EL-001.webm](https://github.com/tuberry/extension-list/assets/17917040/62b77146-30ca-457e-b329-03df4ff11775)
