### ISSUE TITLE
Change in UI / Different icons

### ISSUE THREAD

**Issue by ShrirajHegde** [tuberry/extension-list#6]
![image](https://user-images.githubusercontent.com/66936172/126908720-cbf4dffb-dfc5-4799-b324-c255c82afd39.png)

The extension is amazing but the UI is very very confusing especially since the icons aren't really intuitive(except for remove) and hovering on them gives no clue.

**Comment by tuberry** [comment]
All the features are similar to the Extension app, even though the cherry-picked symbolic icons may not look intuitive enough. Do you have any other suggestions? You could explore the icons in the current icon theme from `gtk4-icon-browser` (usually provided by the `gtk4-demos` package).
Adwaita icon theme:
![Adwaita](https://user-images.githubusercontent.com/17917040/126919207-620074f8-8819-4837-979f-8b257faffd14.png)
Papirus icon theme (It looks good to me):
![Papirus](https://user-images.githubusercontent.com/17917040/126919239-92c825ed-ac7b-45da-b38d-5e92f4008ef6.png)
They mean, from left to right, opening the Extension app, (un)hiding disabled extensions from the menu, toggling the website button in each menu entry and hiding extensions from the menu.
As for designing new and appropriate icons, I probably don't have enough time and energy to do it. :)

**Comment by ShrirajHegde** [comment]
Is there any way to have labels, instead of or below the icons?

How about moving the toggle enable/disable and extension settings  to the right of the extension like extension.gnome.org provides and then use text labelled icons+buttons at the bottom (only 3 icons would be leftover)

>As for designing new and appropriate icons, I probably don't have enough time and energy to do it. :)

I think icons aren't necessary at all. Instead labled buttons would be better

This is a great extension since the latest gnome extensions app auto-updates extension with no way of disabling auto update.

**Comment by tuberry** [comment]
I agree that text labels or colorful buttons (with icon or not) in spacious places, like the Extension app or the e.g.o website, provide better usability than symbolic icons only. 

Extension:
![extapp](https://user-images.githubusercontent.com/17917040/127080221-d79861a1-182d-4444-87c7-5f4ee70964f5.png)

e.g.o:
![ego](https://user-images.githubusercontent.com/17917040/127079861-2afc1dcb-e616-4b7e-9da1-cca2741189b5.png)


But there is too little space (small than a mobile phone) for too much text. Moreover, it is difficult to describe the function of each button in a single word. 

![ext](https://user-images.githubusercontent.com/17917040/127080367-d46a5c52-d945-44ef-ab48-1fed44e9be98.png)

This is a simple extension that focuses on quick access, and for that reason even uses icons instead of a preferences page.

If all the icons were grouped together after each extension name, the user might have to be more careful when clicking on one of them to avoid clicking on the others by mistake. :)

**Comment by axelsimon** [comment]
I think this issue should be reopened.

The problem isn't solved: the icons make no sense to someone opening the app for the first time.

Also, icons without text are known for being terrible, UX-wise, as their meaning can often not be derived from context and lead to the user randomly clicking on icons to try and understand what they do, or just give up entirely. This is the case here. On a personal note, after 5 minutes of clicking the icons, i've only understood some of the icons, and that they do very different things although they are presented as equals, all on the same line.

> But there is too little space (small than a mobile phone) for too much text.
You could take inspiration from Gnome's menu. It puts one item per line, with the text next to it.

> Moreover, it is difficult to describe the function of each button in a single word.
It doesn't need to be a single word, but in any case i'm a bit doubtful of this.  And if it really is, then it sounds like the function might not be tightly defined enough.

Here are some names i could come up with in 5 minutes:
- puzzle: ??
- wrench: ?? (start new Gnome Shell, for some reason?)
- smiley: toggle active extensions
- gear: toggle extension settings
- carriage return: toggle extension ??
- bin: toggle extension deletion

Having a wrench _and_ a gear in the same area is also very confusing.

Hope this helps!

**Comment by tuberry** [comment]
@axelsimon, do you mean split these one-liner buttons onto multiple lines? For example:

![per-line](https://user-images.githubusercontent.com/17917040/132529551-42c26423-36be-444d-ba26-345179d3cea5.png)

@ShrirajHegde, how do you think of that? :)

**Comment by ShrirajHegde** [comment]
> @ShrirajHegde, how do you think of that? :)

This is great! It is 10x more intuitive for me.

One suggestion from my part would be , how feasible is it to put (on/off) toggle, settings, and delete side by side. Like extensions.gnome.org does it

![image](https://user-images.githubusercontent.com/66936172/132534116-cdd1fbd0-22ab-4f97-b6ad-0562451831d9.png)

**Comment by tuberry** [comment]
>One suggestion from my part would be , how feasible is it to put (on/off) toggle, settings, and delete side by side. Like extensions.gnome.org does it

Does that switch matter? Currently, there is a dot per item to indicate the extension status, click to turn it on and off, in this extension. A switch takes up a bit too much space as an indicator, IMHO.

**Comment by tuberry** [comment]
I have made some changes. You can try it from GitHub and change the `shell-version` field in [metadata.json](https://github.com/tuberry/extension-list/blob/master/extension-list%40tu.berry/metadata.json#L7).  Then re-login to enable the extension.

```bash
git clone https://github.com/tuberry/extension-list.git && cd extension-list
sed -i 's/41/your_gnome_shell_version/' extension-list@tu.berry/metadata.json 
make && make install
```

But the English strings may need some improvements. @axelsimon 
@ShrirajHegde, now you can click the plus sign to allow more buttons, and use the switch instead of the dot via `dconf` (requires restarting the extension to take effect):

```bash
dconf write /org/gnome/shell/extensions/extension-list/use-switch true
```

Feedback welcome!

**Comment by jacksongoode** [comment]
It seems the verbose mode toggle is missing in the latest release. I actually would prefer the more simple icon based UI. Would it be possible to add the toggle back?

**Comment by ddnexus** [comment]
Problem related with the icons: for some reasons, if you have too many extensions, the menu will not be limited to the screen height but will go off-screen, so the lowest entries (and the icons) will be unreachable off-screen.

**Comment by NoahTheDuke** [comment]
Any updates on this?

**Comment by tuberry** [comment]
@ddnexus Cannot reproduce. It should be scrollable for that,  see #3.

![sc 2022-08-06](https://user-images.githubusercontent.com/17917040/183243266-6fa1180e-eb1b-430d-b9f7-23230af64d60.png)

**Comment by tuberry** [comment]
We have a prefs page instead of the verbose menu, for a bonus, now these icons could be disabled.
